### ISSUE TITLE
One-tap sign in does not work

### ISSUE THREAD

**Issue by tuomas2** [Ellie-Coding/google-one-tap-drive#1]
Thanks for your demo app! 

I set up your app successfully for "Legacy sign in". It works perfectly and data is stored / loaded from drive correctly.

However, "One-tap sign in" gives always "10: Developer console is not set up correctly". Testing on API 31 Android emulator.
Any idea what is wrong?

**Comment by avalanchas** [comment]
Hi, did you add the `web_client_id` from your own Google Cloud in the `config.xml`? 
You can follow this tutorial to set it all up: 
https://stackoverflow.com/a/75585624/1955202

**Comment by tuomas2** [comment]
Yes I did, and all other steps to the letter I believe.

**Comment by avalanchas** [comment]
Hm, too bad. You can't help but love those super precise google error codes... 
I just checked, the one-tap-signin with this demo still works for me, so I suspect something in your Google Cloud Config is off

Did you make sure to upload the SHA-1 fingerprint of the **debug** variant of your app? Did you use the **web**_client ID instead of the client ID in the config? Does your cloud console look something like this?
![image](https://user-images.githubusercontent.com/6008266/234493754-c3a1c8cb-28a3-48b4-a5be-6745e916699f.png)


I had really hoped this project could be the definitive working demo. Please leave a PR if you ever find out what the problem is. Very sorry I can't help more

**Comment by tuomas2** [comment]
> Hm, too bad. You can't help but love those super precise google error codes... I just checked, the one-tap-signin with this demo still works for me, so I suspect something in your Google Cloud Config is off
> 
> Did you make sure to upload the SHA-1 fingerprint of the **debug** variant of your app? Did you use the **web**_client ID instead of the client ID in the config? Does your cloud console look something like this? 

Okay. Web client(!!!), not Android client. Now it works but I must say that it makes zero sense to me. Thank you!
